use 'defaultdb';
go;

-- create proc InsertDateToUser 
-- create proc InsertDateToAdmin 
-- create proc InsertDateToLearner 
-- create proc InsertDateToInstructor 
-- create proc InsertDateToVipInstructor 
-- create proc InsertDateToCategory 
-- create proc InsertDateToSubCategory 
-- create proc InsertDateToCourse 
-- create proc InsertDateToCourseObjective 
-- create proc InsertDateToSection
-- create proc InsertDateToItem 
-- create proc InsertDateToItemHistory 
-- create proc InsertDateToLecture 
-- create proc InsertDateToLectureSubtitle 
-- create proc InsertDateToQuiz 
-- create proc InsertDateToQuizQA 
-- create proc InsertDateToQuizQAAnswerDetail 
-- create proc InsertDateToStudentAnswerQA 
-- create proc InsertDateToQuestion 
-- create proc InsertDateToAnswer 
-- create proc InsertDateToShoppingCart 
-- create proc InsertDateToEnrollementCourse 
-- create proc InsertDateToCourseInstructor 
-- create proc InsertDateToCourseInstructorHistory 
-- create proc InsertDateToCourseProgress 
-- create proc InsertDateToAdjustment  
-- create proc InsertDateToNotification
-- create proc InsertDateToPromotionalProgram
-- create proc InsertDateToPromotionalProgramHistory
-- create proc InsertDateToPriceConversion
-- create proc InsertDateToCourseHighlight
-- create proc InsertDateToPayment
-- create proc InsertDateToMonthlyCourseIncome
-- create proc InsertDateToMonthlyCourseIncomeVipInstructor